language: bash
services: docker

env:
  - VERSION=3 VARIANT=
  - VERSION=3 VARIANT=slim
  - VERSION=2 VARIANT=
  - VERSION=2 VARIANT=slim

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="pypy:$VERSION${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
